### ISSUE TITLE
2FA doesn't work, not even with app-password

### ISSUE THREAD

**Issue by JoSSte** [mobeigi/fb2cal#105]
With 2FA activated, his script just fails with `Failed to authenticate with Facebook with email {email}. Please check provided email/password.`  

App-Password article on fb help:
https://www.facebook.com/help/249378535085386/

**Comment by JoSSte** [comment]
I Re-read the docs and discovered that I had missed the "no quotes" comment in the fill out `config/config.ini` step. didn't help though...

**Comment by JoSSte** [comment]
verified that the script works with user with no 2fa enabled - works beautifully

**Comment by mobeigi** [comment]
This is a duplicate of https://github.com/mobeigi/fb2cal/issues/9 and also mentioned in the README.
2FA isn't supported at all right now. Glad it worked with no 2FA for you 👍
