### ISSUE TITLE
No results for current month (August)

### ISSUE THREAD

**Issue by jonicunha** [mobeigi/fb2cal#106]
Hi,

Like issue #97 , at this moment the app is not getting any results for current month (August). In the ICS file there are no entries with
DTSTART;VALUE=DATE:202108... or DTSTART;VALUE=DATE:202208...

I extracted them today - 16/08/2021 - and I checked on Facebook Page that I have birthdays this month.
I'm using v1.2.3

Can you verify please?

**Comment by mobeigi** [comment]
Hi @jonicunha,

Using `v1.2.3` and generating the file I was able to find birthdays for the current month of August (i.e. I found `DTSTART;VALUE=DATE:202108` entries in the ICS).

Can you try again and see if you are still running into this issue?

From Facebook's page I see they still have all months working fine for me except for `July` of next year (i.e. the 11th offset month from the current month) which is still an existing bug from the other issue.

**Comment by jonicunha** [comment]
Hi @mobeigi 

I still have the same problem, I don't know if it helps but below you can find the log file
I even reconfigured everything again but without success.

[fb2cal.log](https://github.com/mobeigi/fb2cal/files/7032749/fb2cal.log)

As you can see I have more birthdays today and this month:
![image](https://user-images.githubusercontent.com/53365164/130466883-12b15473-aec4-4bd6-88de-8c8b0d1d5a40.png)

![image](https://user-images.githubusercontent.com/53365164/130466673-1ee1e059-ed16-4929-8545-51dc702cb5bc.png)

Thank you.

**Comment by mobeigi** [comment]
Hi @jonicunha,

You seem to be running a very old version. From the logs `Starting fb2cal v1.1.0 (Production)`.

Try downloading and resetting up the latest version and trying again.

**Comment by jonicunha** [comment]
I did that.
A few minutes ago I downloaded fb2cal v1.2.0 and than updated files latest version v1.2.3
I did that because only the version 1.2.0 have the SRC folder.

**Comment by mobeigi** [comment]
@jonicunha Your log file should say `v1.2.3` if you did it correctly.

Follow the instructions in the `readme` page from scratch.
You might have to do a `pipenv uninstall fb2cal` first though.

**Comment by jonicunha** [comment]
@mobeigi 

That solved my problem!

Thank you.
