### ISSUE TITLE
Create yearly occurrence events instead of the next year only

### ISSUE THREAD

**Issue by sineline** [mobeigi/fb2cal#107]
When the calendar is exported, events are only stored for the upcoming 12 months. I would suggest to add the option to transform those events into a yearly recurrent events instead.

**Comment by mobeigi** [comment]
Hi @sineline ,

We already have this feature in the ICSWriter code:
`e.extra.append(ContentLine(name='RRULE', value='FREQ=YEARLY'))`

This makes it a yearly reoccurring event according to the ICS RFC standard.
I have tested this and it works with Google Calendar as an example.

It is important to note the ICS does not contain any birthdays in the past from the date it was generated though, so those will be missing.

Maybe the calendar software you are using does not support this feature?

**Comment by sineline** [comment]
You are absolutely right. My bad, I must have messed something with my calendar.
