### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cbraukmann** [mobeigi/fb2cal#19]
![error](https://user-images.githubusercontent.com/17256374/62298254-f28b5600-b472-11e9-967f-fd142de8ee33.JPG)

Hi, i am getting this error when trying to start the script.

I followed your instructions exactly.

**Comment by mobeigi** [comment]
You have to use python3.6+ instead of older python versions.

See **Requirements** in [readme](https://github.com/mobeigi/fb2cal/blob/master/README.md#requirements).
