### ISSUE TITLE
Facebook Async Page Not Available

### ISSUE THREAD

**Issue by MayeulChassagnard** [mobeigi/fb2cal#22]
Following link to get birthdays is not available anymore:
https://www.facebook.com/async/birthdays/?
ref code line: https://github.com/mobeigi/fb2cal/blob/master/src/fb2cal.py#L373

![image](https://user-images.githubusercontent.com/20341270/62412243-b76a5d80-b5ff-11e9-8c6f-7a515163bf68.png)

**Comment by mobeigi** [comment]
It is available. You are just missing all the query parameters.

Example query (replace PUT_DTSG_HERE with the dtsg token) :
```
https://www.facebook.com/async/birthdays/?date=1567321200&fb_dtsg_ag=PUT_DTSG_HERE&__a=1
```

**Comment by MayeulChassagnard** [comment]
Oh, okay, I don't know why it does not go to the end then :( 
It prints few lines like `DEBUG (_make_request) https://www.facebook.com:443 "GET ...` after `Processing birthdays for month August.` and stop without any issues

**Comment by mobeigi** [comment]
@MayeulChassagnard Script is pretty slow, it will take a fair bit of time to run. Takes ~3 minutes for me each run. If you are running into issues, you should enable `DEBUG` level logging in the `config.ini` file and look at the full logs.

**Comment by MayeulChassagnard** [comment]
@mobeigi Thank you very much for your help! I'm testing this right now

**Comment by MayeulChassagnard** [comment]
Well, looks like the character **`ï`** make it crash without any warning or crash logs

**Comment by mobeigi** [comment]
Ah that is unfortunate. Yeah the code probably isn't fully compliant with unicode characters. Some work has to be done to sort that out!

**Comment by mobeigi** [comment]
Closed. See #24 for further details.
