### ISSUE TITLE
Step by step instructions for Non-IT-Experts on Windows?

### ISSUE THREAD

**Issue by Scorten** [mobeigi/fb2cal#23]
I'm not really an IT-expert and I also do not use Linux. So I literally don't know what I have to do. I just want my friends' birthdays back in my Google Calendar :/ 

Is there any possibility of having an easier installation or some instructions for dummies? I'm already confused by step 1, but I'm assuming that this is only relevant for Linux users. So I skipped this and continued with step 2. I don't even know what these words mean (e.g. "Create OAuth consent screen if required").

**Comment by mobeigi** [comment]
Hey @Scorten , I'm hoping to eventually add an 1 click installer to make it easier for non-developers to use this tool. You'd essentially just install a program as normal, configure it via a GUI and then it would just work without any extra setup!

This is planned work for #15 

Another useful option would be a Youtube video I suppose on how to setup the current solution. I'll try to make a Youtube video too where I go super in depth into each step to make it all clear. When that is out I will let you know.

Closing this for now.
