### ISSUE TITLE
Special characters stored as html entity codes in ICS file

### ISSUE THREAD

**Issue by 3rasernl** [mobeigi/fb2cal#25]
The names with differences to the letter "e" are not correctly displayed. So far I only noticed the following:

ę = &#x119;   Feręc  becomes Fer&#x119;c's
é = &#xe9;    Fréderique becomes Fr&#xe9;derique
ë = &#xeb;    Zoë becomes Zo&#xeb;

**Comment by mobeigi** [comment]
I'm a little confused. You posted the same letters and names twice which match.

Maybe post a picture instead?

**Comment by 3rasernl** [comment]
very dumb mistake on my end. Here are some pics

![image](https://user-images.githubusercontent.com/22075724/62431731-32c82e00-b72a-11e9-9053-4ba1d3713b0d.png)

![image](https://user-images.githubusercontent.com/22075724/62431742-5be8be80-b72a-11e9-9702-ec87c25bd30f.png)

**Comment by mobeigi** [comment]
So yes in the ICS file the name is stored as the html entity codes. However, it should display properly on Google Calendar right? But good point, it may not display properly in other third party apps and maybe storing the special character directly is a better idea.

**Comment by Monkler** [comment]
I also run into this problem.
it is not displayed in the google calender right.
Its because you are using the "data-tooltip-content" instead of the display name it is HTML encoded value. 


I just made an HTML unescape for the names:

`birthdays.append(Birthday(uid, html.unescape(name), day, month))`

**Comment by mobeigi** [comment]
@Monkler Good stuff, want to make a pull request? 👍
