### ISSUE TITLE
Stuck at step 6

### ISSUE THREAD

**Issue by moey101** [mobeigi/fb2cal#42]
First off thanks for the tool.
Second: I'm NOT a dev, nor anything like that. But can follow (easy and simple) steps.
Third: Working on a Mac.
Fourth: Did everything that was explained in the Readme file and ended up with the following upon starting step 6 (Run script manually once for testing purposes: python ....../src/fb2cal.py)
```
File "src/fb2cal.py", line 60
    return f'{self.name} ({self.day}/{self.month})'
                                                  ^
SyntaxError: invalid syntax
```
Did I do something wrong or is it just that Mac ain't supported? Want to create the file once only, not as a regular thing. Stopped Facebook-2FA for this procedure before starting with the first step.
Thanks for any help!

**Comment by mobeigi** [comment]
Hey @moey101 , Looks like you are using a version of python older than 3.6 in which case those f strings won't work. You will have to update to a newer version of python.

You can check my typing:
```python -V```

Example output:
```
C:\Users\Mo>py -3 -V
Python 3.7.4
```

**Comment by moey101** [comment]
Shoot, you're correct, turns out I'm using Python 2.7. So for regular Mac users they should start off with installing XCode if not done yet: 
`$ xcode-select --install`
and then load up Homebrew
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
and then proceed with the steps you have given and alternating 2 lines: 
Step 5 should be 
`pip3 install -r requirements.txt`
and step 6 should be 
`python3 src/fb2cal.py`

Worked great in the end, thanks a lot!
