### ISSUE TITLE
Syntax error when I run fb2cal.py 

### ISSUE THREAD

**Issue by aamnakhan** [mobeigi/fb2cal#43]
At this point of the setup process - https://youtu.be/UnsbV8EJ8-Y?t=259
I get the following error -
```
 File "src/fb2cal.py", line 73
    CONFIG_FILE_PATH = f'../config/{CONFIG_FILE_NAME}'
                                                     ^
SyntaxError: invalid syntax
```
Using Python 3.7.3, requirements.txt modules installed. On V1.0.3 - Point Release of the repo. 

Has anyone faced this issue?

**Comment by mobeigi** [comment]
Doesn't look like you are using Python 3.6+.

Try this command and see what version it prints out:
`python -V`

**Comment by calvinle** [comment]
Depending on the environment, ensure you're running `python3 fb2cal.py`

**Comment by Sohardh** [comment]
If i run it on python3 then mechanicalsoup is not working

**Comment by foxryan** [comment]
If you're running multiple versions of Python (e.g. the default version on Mac and Python3), make sure you install the requirements specifically within your Python3 path.

`python3 -m pip install -r requirements.txt`
