### ISSUE TITLE
WARNING (get_entity_id_from_vanity_name) Falling back to getting entity id from profile page for vanity name

### ISSUE THREAD

**Issue by benjybarkes** [mobeigi/fb2cal#45]
Script worked really well (on a Mac) when i ran it first time for my profile then tried running it again for my girlfriends.

Script ran rapidly through the first 6 months then suddenly slowed right down and displayed the following message for every name:

"fb2cal WARNING (get_entity_id_from_vanity_name) Falling back to getting entity id from profile page for vanity name example.name. This method is significantly slower."

Seems strange that it was fine for mine and also the first 6 months of hers?

**Comment by calvinle** [comment]
I ran this about three times, first two I came across errors with an earlier mentioned issue with ics. By the third run I got the same error.

**Comment by mobeigi** [comment]
Excerpt from my blod post:
http://bit.ly/fb2cal-blogpost

`
Rate limiting note: If the composer query endpoint is hit enough in a short period of times, it seems to somehow restrict the number of entries returned. It seems to limit the query results to only returning results matching friends names, page names exactly. This limitation then disappears over time. So one should be careful how often or quickly they hit this endpoint!
`

You probably reached this rate limit by sending too many requests in a short period of time from the same IP/account etc. I suggest you wait 1-2 days without using the script and the limitation should disappear.

There is no other work around really besides finding another effecient way to convert a vanity name to a Facebook ID. There probably are other endpoints that can be used but you'll have to search for them.

**Comment by benjybarkes** [comment]
Got it. Many thanks for explaining. Great script thanks for developing!

**Comment by mobeigi** [comment]
This should no longer be an issue at all thanks to #65. There should be no rate limited and script will be much faster.
