### ISSUE TITLE
Authentication for Device Not getting

### ISSUE THREAD

**Issue by likeitaash** [mobeigi/fb2cal#58]
How to give the device authorization manually on Facebook? It had asked to do that. How should I go for it.
![image](https://user-images.githubusercontent.com/60418604/78073884-5037bf80-73bf-11ea-86c2-0bdea58b2ce4.png)
can uh solve it.

**Comment by POIZ87** [comment]
getting this too. either with drive or file version

**Comment by romeusantiago** [comment]
@likeitaash and @POIZ87, I was having the same trouble! I verified that the problem was with 2 factors authentication so I disabled and tested it. It works like magic.

**Comment by likeitaash** [comment]
And how to do that....

**Comment by romeusantiago** [comment]
In Facebook, at the right corner you go to Configuration and Privacy. After that, click on the "Security and Login" option. There you gonna see one option "Use Two Factor Authentication".

Edit and disable and it gonna work.

P.s.: After my sync was done and I have what I need, I've enabled again, ok?!

Best regards and feel free to get in touch.

**Comment by mobeigi** [comment]
If the security checkpoint is triggered you are required to log into Facebook in a browser (you may have to log out first) and then follow the prompts to verify your account. This cannot be avoided as it is a Facebook security mechanism.
