### ISSUE TITLE
Found 0 birthdays for month X

### ISSUE THREAD

**Issue by cggaurav** [mobeigi/fb2cal#59]
```
[2020-04-09 19:55:22,354] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month April.
```
And for every other month I get a similar log. And I am pretty sure I have friends and they have birthdays :)

**Comment by mobeigi** [comment]
See the **Troubleshooting** section in readme.

I wouldn't be able to tell much more without seeing the logs.
