### ISSUE TITLE
No .ics file was created

### ISSUE THREAD

**Issue by nenyalorien** [mobeigi/fb2cal#67]
- I used the Local File process.
- I turned off 2FA. 
- I updated pip. 

Let me know if you need the log file. :D

**Comment by mobeigi** [comment]
Yeah more info would be good. Have a look at the **Troubleshooting** section in readme also on how to enable debug loggging.

**Comment by gogvale** [comment]
I used pipenv and no quotes on email/password. Worked like a charm
