### ISSUE TITLE
Mechanical Soup Error

### ISSUE THREAD

**Issue by batyrchary42** [mobeigi/fb2cal#71]
Hi guys, 

I have cloned and trying to run the script. MechanicalSoup package is installed in my machine. But, I am receiving error below. 

```
bash-3.2$ pipenv run python /Users/.../Documents/git/fb2cal/src/fb2cal.py
Traceback (most recent call last):
  File "/Users/..../Documents/git/fb2cal/src/fb2cal.py", line 25, in <module>
    import mechanicalsoup
ModuleNotFoundError: No module named 'mechanicalsoup'
```

**Comment by mobeigi** [comment]
Hmm looks like it might be running with python 2 instead of python 3.6+?

Try: 
`pipenv run python3 /Users/.../Documents/git/fb2cal/src/fb2cal.py`

**Comment by mobeigi** [comment]
Also are you sure you followed setup instructions correctly?
You have to run `pipenv install` first.

**Comment by batirch** [comment]
```
~ ...$ pipenv install
Installing dependencies from Pipfile.lock (db4242)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
(base) MacBook-Air-2:~ ...$ pipenv shell
Launching subshell in virtual environment…
bash-3.2$  . /Users/.../.local/share/virtualenvs/...-mPLkNOWd/bin/activate
(...) bash-3.2$ pipenv run python3 /Users/.../Documents/git/fb2cal/src/fb2cal.py
Traceback (most recent call last):
  File "/Users/.../Documents/git/fb2cal/src/fb2cal.py", line 25, in <module>
    import mechanicalsoup
ModuleNotFoundError: No module named 'mechanicalsoup'

``

**Comment by mobeigi** [comment]
You don't need to run `pipenv shell`, just `pipenv run` directly.
That might not fix it though.

**Comment by batirch** [comment]
Could it be because of installed folder? 

```
(base) MacBook-Air-2:~ ...$ pip show MechanicalSoup
Name: MechanicalSoup
Version: 0.12.0
Summary: A Python library for automating interaction with websites
Home-page: https://mechanicalsoup.readthedocs.io/
Author: UNKNOWN
Author-email: UNKNOWN
License: MIT
Location: /Users/.../opt/anaconda3/lib/python3.7/site-packages
Requires: beautifulsoup4, six, requests, lxml

``

**Comment by filmgeek5000** [comment]
Hello, i've had the same exact issue. Any update?

**Comment by mobeigi** [comment]
@filmgeek5000 Are you also on a Mac? I am not able to reproduce the problem myself.

**Comment by filmgeek5000** [comment]
Yes I am on a Mac Mini running High Sierra

**Comment by mobeigi** [comment]
@filmgeek5000 I can't reproduce it myself on a Mac system so its a little hard to fix.

Are you using the latest version of the files?
Are you following the steps as listed in the readme?

**Comment by filmgeek5000** [comment]
yes

**Comment by mfvo** [comment]
I have the same issue :(

**Comment by mobeigi** [comment]
@mfvo Are you able to provide any more information about your system/environment? I cannot reproduce this issue myself so its hard to fix.

**Comment by mfvo** [comment]
> @mfvo Are you able to provide any more information about your system/environment? I cannot reproduce this issue myself so its hard to fix.

I have the last mac os software, I mean 10.15.6 and running Python 3.7

**Comment by krullebolle** [comment]
Hi,

I had the same issue on linux and windows, latest python3.
Was able to run the script, after manually installing the mechanicalsoup module with `pip install mechanicalsoup` and after that restarting the virtual environment.

Kind regards

**Comment by viktorcsimma** [comment]
Try to change the active directory to the directory of the package, that helped me (I downloaded it into a zip file and then extracted it).

**Comment by jamestamplin** [comment]
I also ran up against this error.

Fresh install of MacOS 10.15.7 Catalina
Fresh install of Homebrew / Python / Pip
Checked that I was running Python 3.9

I ran `pipevn run python -m fb2cal` and hit the `ModuleNotFoundError: No module named 'mechanicalsoup'` error

I was able to get around this by running

`pipenv install mechanicalsoup`

Which then got past that error, but ended up with not finding the ics module, fixed that by running

`pipenv install ics `

...and Bob's your uncle, it worked.

Thanks for this great little script!

**Comment by mobeigi** [comment]
@jamestamplin 

Did you run `pipenv install` first?
That should have installed `mechanicalsoup` and `ics` based on the **requirements.txt** file.

I have a Mac but can't reproduce this on mine.
Maybe I'm misusing `pipenv` or its behaving differently on macos. 🤔

**Comment by jamestamplin** [comment]
I did run pipenv install first (though, on second though, perhaps I ran it
from the wrong directory).

Sorry that's not more helpful.

**Comment by nufrankz** [comment]
> I also ran up against this error.
> 
> Fresh install of MacOS 10.15.7 Catalina
> Fresh install of Homebrew / Python / Pip
> Checked that I was running Python 3.9
> 
> I ran `pipevn run python -m fb2cal` and hit the `ModuleNotFoundError: No module named 'mechanicalsoup'` error
> 
> I was able to get around this by running
> 
> `pipenv install mechanicalsoup`
> 
> Which then got past that error, but ended up with not finding the ics module, fixed that by running
> 
> `pipenv install ics `
> 
> ...and Bob's your uncle, it worked.
> 
> Thanks for this great little script!

Confirming this on MacOSX Catalina 10.15.7, Python 2.7.16, PipEnv 2020.11.15.

**Comment by mobeigi** [comment]
This issue has been fixed as part of: https://github.com/mobeigi/fb2cal/pull/116

It was a result of various imports in `__init.py__`:
```
from .transformer import *
from .facebook_user import *
from .facebook_browser import *
from .ics_writer import *
```

Causing an early dependency failure to occur before SetupTools initialised and was ready to import dependencies.
The refactor now solves this issue.
