### ISSUE TITLE
fb2cal ERROR (main) config/config.ini does not exist. 

### ISSUE THREAD

**Issue by pablobiedma** [mobeigi/fb2cal#72]
it says:  fb2cal ERROR (main) config/config.ini does not exist. Please rename config-template.ini if you have not done so already.

However I have done so already: 
![image](https://user-images.githubusercontent.com/43525988/86641211-42f02980-bfdb-11ea-9189-3573d48bf98d.png)

what should I do?

**Comment by pablobiedma** [comment]
I solved this just by renaming config.ini to just config
![image](https://user-images.githubusercontent.com/43525988/86643987-6d42e680-bfdd-11ea-9aae-453332987688.png)

**Comment by mobeigi** [comment]
As a heads up it looks like you have the `hide known file extensions` enabled on Windows which means the first file was actually called `config.ini.ini` and the second one `config.ini` which is why it worked. 😄
