### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by gioluca2** [mobeigi/fb2cal#8]
I have this error:

$ git clone git@github.com:mobeigi/fb2cal.git
Cloning into 'fb2cal'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mobeigi** [comment]
That is a generic git issue.
Make sure you have your SSH keys setup properly.

Alternatively clone via HTTP:
https://github.com/mobeigi/fb2cal.git

Or use the download repo as ZIP.
