### ISSUE TITLE
1.2.1 issues

### ISSUE THREAD

**Issue by VladimirBelov** [mobeigi/fb2cal#85]
1. no fb2cal.py file just __main__.py. need to update readme files
2 after running __main__.py just "ImportError: attempted relative import with no known parent package" error
3. version 1.1.0 worked fine in july but now it trigger facebook security prompt

1.2.1 output:

ics_writer.py
Traceback (most recent call last):                                                                                                                      
File "ics_writer.py", line 9, in <module>                                                                               
 from .logger import Logger                                                                                                                     
   ImportError: attempted relative import with no known parent package

**Comment by mobeigi** [comment]
The readme is updated and looks good to me.

You are not running the code as a module mode which is your problem.
I also assume you are not using pipenv.

Do this to run the code:
`python -m fb2cal`

This will run the `fb2cal` folder as a python module (`-m` flag).

Once you do this, it should run without problems.

Also the security prompt has nothing to do with how this script works. It is Facebook flagging your account if they believe you have been hacked which can happen if you constantly login multiple times using this script in a short amount of time.

If the prompt error is received, log into Facebook normally and reset your password. Then it is a good idea to way a few days to let the system cooldown before running this script again.
