### ISSUE TITLE
Events showing as Busy

### ISSUE THREAD

**Issue by ScottBishop** [mobeigi/fb2cal#86]
I added these events to Outlook and they are showing as Busy and blocking my entire calendar. Is there an option to change this and/or remove all the events?

**Comment by mobeigi** [comment]
These events are marked as 'All Day' events.
This is the `DURATION:P1D` in the ICS file.

I'm not an Outlook user but this does not seem to be a problem with this tool.
Perhaps considering adding this as a secondary calendar in outlook.
