### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by Urong** [mobeigi/fb2cal#95]
I am using python 3.7.9
When trying to run fb2cal, I get the below Traceback:

```
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "fb2cal\__main__.py", line 24, in <module>
    from .ics_writer import ICSWriter
ImportError: attempted relative import with no known parent package
```

**Comment by mobeigi** [comment]
Hmm that is odd.

Are you following the instructions from the readme carefully?
I just tested `master` on repl.it and its working with no issues for me.

**Comment by Urong** [comment]
Got it.  It's actually my bad, I tried running it from natives' venv instead of pipenv.  Using pipenv solved the issue. it works like a charm great work.  Sorry for the dumb question.
