### ISSUE TITLE
Facebook password wrong: wrong output

### ISSUE THREAD

**Issue by dag7dev** [mobeigi/fb2cal#96]
![immagine](https://user-images.githubusercontent.com/44711271/115663634-18d8df80-a341-11eb-95ed-217c1f0a119e.png)
It says "Facebook user list is empty". This is simply not true, since I entered an incorrect password it should say "wrong password".

Python version: 3.9.0
OS: Windows 10 Version 10.0.19042 Build 19042
Architecture: x64

**Comment by mobeigi** [comment]
Howdy,

The method in which we check if login successful is quite hacky.
We do some `200` checks and check to see if certain elements exist in the DOM.

This would be improved if we did an extra network call to some privileged endpoint although it's low priority.

Out of curiosity, is your FB language non-English?

**Comment by dag7dev** [comment]
OOT: all it started because I typed wrong password by mistake and it told me that error.
I triple checked out that password, finding out that I was wrong (obviously) and the tool works great!

To answer your question: Ding-ding-ding! Correct!

Honestly I don't know how you managed to scrap the website, but to check if a user is log or not I could advise to simply check if c_user in cookies is set or not for facebook.com

In fact, that represents your userid, which it would be null if you are unlogged or with invalid credentials.

**Comment by mobeigi** [comment]
Sounds like a good plan.
Feel free to put up a PR if you can :)
