### ISSUE TITLE
Adding this feature to magic mirror

### ISSUE THREAD

**Issue by websterjazz** [mobeigi/fb2cal#99]
Hi, I am a newbie and am using my raspberry Pi as magic mirror... I was wondering if there is a way to add FB birthdays ical calendar to the magic mirror app?

**Comment by mobeigi** [comment]
Hi @websterjazz , 

I'm not too familiar with magic mirror but this seems like a pretty specific request which isn't the purpose of this tool. Your best bet is probably using a computer to extract your Facebook friends birthdays and then put them up on a calendar app for the magic mirror.
